# Train Test Split

In [1]:
import numpy as np
from sklearn.model_selection import train_test_split

### Generating some data we are going to use

In [2]:
a = np.arange(1, 101)
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [3]:
b = np.arange(501, 601)
b

array([501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513,
       514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526,
       527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539,
       540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552,
       553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565,
       566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578,
       579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591,
       592, 593, 594, 595, 596, 597, 598, 599, 600])

### Spliting the data

In [4]:
# train_test_split takes a dataset and splits into two datasets
train_test_split(a)

[array([ 95,  35,  99,  45,  59,  49,  65,  58,  50,  54,  44,  29,  23,
         86,  10,  14,  81,  98,  66,   2,  25,  34,  18,  92,  68,  20,
         71,  33,  62,  87,  31,  64,  42,   8,  24,  69,  75,  60,  84,
         51,  82,  53,  78,   6,  17,  72,  80,  19,  90,  79, 100,   1,
         61,  94,  21,  56,  37,  52,   5,  77,  46,  74,   9,  22,  36,
         89,  48,  93,  28,  96,   4,  57,  32,  11,  13]),
 array([41, 12, 26, 88, 83, 70, 40, 43, 97, 73, 76, 39, 55, 47, 63, 67, 85,
        16, 91, 27, 30,  7, 15, 38,  3])]

In [5]:
a_train, a_test = train_test_split(a)

### Explore the results

In [6]:
a_train.shape, a_test.shape

((75,), (25,))

In [7]:
a_train

array([ 5, 85, 71, 99, 56, 14, 22, 21, 51, 50, 19, 42,  9, 18, 83, 65, 29,
       79, 16, 78, 66, 70, 36, 32, 37, 40, 41, 74, 88, 39,  3, 44, 91, 68,
       63, 75, 17, 80, 15, 31, 89, 77, 12, 76, 38, 27, 64, 20, 35, 61, 59,
       53, 23, 46, 97, 33, 84, 30, 86,  4, 98, 34, 28, 57, 52, 69,  1, 90,
       47, 93, 49, 96, 72, 11, 24])

In [8]:
a_test

array([ 94,   8,   2,  54,  62,  95, 100,   7,   6,  58,  48,  25,  45,
        67,  82,  92,  10,  55,  13,  73,  26,  60,  87,  81,  43])

In [9]:
a_train, a_test, b_train, b_test = train_test_split(a,b, test_size=0.2, shuffle=True, random_state=42)

In [10]:
a_train

array([ 56,  89,  27,  43,  70,  16,  41,  97,  10,  73,  12,  48,  86,
        29,  94,   6,  67,  66,  36,  17,  50,  35,   8,  96,  28,  20,
        82,  26,  63,  14,  25,   4,  18,  39,   9,  79,   7,  65,  37,
        90,  57, 100,  55,  44,  51,  68,  47,  69,  62,  98,  80,  42,
        59,  49,  99,  58,  76,  33,  95,  60,  64,  85,  38,  30,   2,
        53,  22,   3,  24,  88,  92,  75,  87,  83,  21,  61,  72,  15,
        93,  52])

In [11]:
a_test

array([84, 54, 71, 46, 45, 40, 23, 81, 11,  1, 19, 31, 74, 34, 91,  5, 77,
       78, 13, 32])